### ISSUE TITLE
Overwriting Human def

### ISSUE THREAD

**Issue by Tachyonite** [Xahkarias/EvolvedOrgansRedux#11]
You should probably be patching the main Human def as opposed to overwriting it and adding parts as it might cause instability, and overwriting Core defs is generally bad practice.

**Comment by Xahkarias** [comment]
You know, I feel really dumb for not realizing that sooner. Thankfully I found a way to implement this without shuffling everyone's already existing defs. Thank you for the great idea!

**Comment by Xahkarias** [comment]
Handled in: https://github.com/Xahkarias/EvolvedOrgansRedux/commit/97f8a0f12d4fb7612abbabe13660271ba94c869f
