### ISSUE TITLE
Race Compat request: Kijin 2.0 and Arachne

### ISSUE THREAD

**Issue by 400kvac** [Xahkarias/EvolvedOrgansRedux#13]
Kijin 2.0:
https://steamcommunity.com/sharedfiles/filedetails/?id=1918120749
Arachne:
https://steamcommunity.com/sharedfiles/filedetails/?id=1589454687

Insofar as I can tell by looking through the implants in Prepare Carefully, they seem to lack the new parts added by this mod, i.e. no left/right chest cavities, left/right abdominal cavities, upper/lower back, tailbone and left/right lower shoulder.

**Comment by Xahkarias** [comment]
covered in https://github.com/Xahkarias/EvolvedOrgansRedux/commit/93c90c949269a818d97ab3d9c2f0f19d3e5e8415
