### ISSUE TITLE
Unable to bring resource in the vat organ

### ISSUE THREAD

**Issue by Mysteriou85** [Xahkarias/EvolvedOrgansRedux#14]
I'm unable to bring the last resource for grow the organ of the mod in the organ vat of QEE, I have the resource and all the research needed but the game tell me "No bills currently queued".

The rest of the organ of QEE seems to work and I can create clone.

My mod list :
-HugsLib
-JecsTools
-Humanoid Alien Races 2.0
-Faction Discovery
-Allow Tool
-Vanilla Factions Expanded - Core
-Vanilla Furniture Expanded
-Vanilla Events Expanded
-Vanilla Fishing Expanded
-Vanilla Hair Expanded
-Vanilla Furniture Expanded - Farming
-Vanilla Furniture Expanded - Production
-Vanilla Furniture Expanded - Medical module
-Vanilla Furniture Expanded - Spacer module
-Vanilla Furniture Expanded - Security
-Vanilla Furniture Expanded - Art
 -Vanilla Animals Expanded - Tropical Swamp
-Vanilla Animals Expanded - Tropical Rainforest
-Vanilla Animals Expanded - Boreal Forest
-Vanilla Animals Expanded - Ice Sheet
-Vanilla Animals Expanded - Thundra
-Vanilla Animals Expanded - Extreme Desert
-Vanilla Animals Expanded - Desert
-Vanilla Animals Expanded - Arid Shrubland
-Vanilla Animals Expanded - Cats and Dogs
-Vanilla Animals Expanded - Livestock
-Vanilla Animals Expanded - Australia
-Vanilla Animals Expanded -
-Vanilla Factions Expanded - Medieval
-Vanilla Weapons Expanded - Medieval
-Vanilla Weapons Expanded - Quickdraw
-Vanilla Armour Expanded
-Vanilla Apparel Expanded
-[1.0] Android tiers
-Android Tiers++ Expansion
-Android Tiers + Vanilla Expanded Medical
-Android Tiers Unfeeling Patch
-More Mechanoids
-Pick Up And Haul
-Hospitality
-Save Our Ship 2
-Interaction Bubbles
-RimHUD
-Medical Tab
-Research Tree
-EdB Prepare Carefully
-Quarry 1.0
-Wall Light
-LWM's Deep Storage
-[JDS] Simple Storage
-Color Coded Mood Bar
-Recipe icons
-Bionic icons
-Questionable Ethics Enhanced
-EvolvedOrgansRedux
-Expanded Prosthetics and Organ Engineering
-Reinforced Walls
-Boats
-[sd] advanced powergeneration
-[FSF] Growable Grass
-Grazing Lands
-Better Infestations 1.0
-Reasonable Components V1
-Death Rattle
-[FSF] Rain Washes Away Filth
-[SYR] Set Up Camp
-Realistic Rooms
-[1.0] RPG Style Inventory

**Comment by Xahkarias** [comment]
Cursory look at modlist makes me feel like it is an EPOE compat problem, will look into it

**Comment by Xahkarias** [comment]
Issue was due to QEE Vats not liking having an organ with over 150 of one reagent

Dealt with in https://github.com/Xahkarias/EvolvedOrgansRedux/commit/3b25069081e393fda2cdda64fee89e18f1da8745
