### ISSUE TITLE
kijin patch troubles

### ISSUE THREAD

**Issue by 1pyro2hell3** [Xahkarias/EvolvedOrgansRedux#17]
as i mentioned on the workshop page i can't install the extra organs for now i'm just going to list the mods in my unsuccessful bare bones test run

modlist 
hugslib
jecstools
humanoid alien races
femalebb body type support
kijin race 2.0
prepare carefully
evolved organs redux

once i can get this working I'll try the rest of my mod one by one and let you know if i find anything

**Comment by Xahkarias** [comment]
Fixed in https://github.com/Xahkarias/EvolvedOrgansRedux/commit/3337969035417ff61a75def57ca1571f96b35ffb
