### ISSUE TITLE
Race Compat: Ferian

### ISSUE THREAD

**Issue by Xk275** [Xahkarias/EvolvedOrgansRedux#23]
https://steamcommunity.com/sharedfiles/filedetails/?id=1611790118

From steam

**Comment by Xahkarias** [comment]
Expect this to be patched on Sunday

**Comment by Xk275** [comment]
Thank you.

**Comment by Xahkarias** [comment]
https://github.com/Xahkarias/EvolvedOrgansRedux/commit/4497ab4403e6d796aab5054823ffd5e71306469b

Will be out in patch 1.0.6
