### ISSUE TITLE
Mod compat request: Pawnmorpher

### ISSUE THREAD

**Issue by Tachyonite** [Xahkarias/EvolvedOrgansRedux#24]
Currently, the tailbone is added regardless of whether another mod adds the part for humans. In PM's case this means that the pawn can have two tails (unless PM is loaded after EOR, since PM checks if it already exists.)

A similar system of checking whether the Tail def exists in the pawn before adding it should fix this and allow the two mods to be loaded in any order relative to each other. :)

https://steamcommunity.com/sharedfiles/filedetails/?id=1786466855&tscn=1581725698

**Comment by Xahkarias** [comment]
You know, every day I realize how bad my code style is lol. Expect this to be on steam on sunday

**Comment by Xahkarias** [comment]
https://github.com/Xahkarias/EvolvedOrgansRedux/commit/34de0d5572eee632e14a37b1548fe15518a3479f
