### ISSUE TITLE
Jaffa Race

### ISSUE THREAD

**Issue by FeatherKamisori** [Xahkarias/EvolvedOrgansRedux#32]
Hi, could you please confirm or ensure compatibility with the Jaffa race from the [O21] Stargate mod please? Thank you. (they are currently in the process of redoing rimhammer40 as well)

https://steamcommunity.com/sharedfiles/filedetails/?id=1998203184

**Comment by Xahkarias** [comment]
Sorry for tardiness, confirmed to work
