### ISSUE TITLE
Can't implant Neural Hyperthreader on the pawn

### ISSUE THREAD

**Issue by Kosolaper** [Xahkarias/EvolvedOrgansRedux#46]
I found out its problem with Expanded Prosthetics and Organ Engineering - Forked mod. With this mod you can install brain organs through prepare carefully but operations for them doesn't show up in operation tab. I still can install them though Medical Tab mod.

**Comment by Xahkarias** [comment]
Interesting, will take a look on how to fix this

**Comment by Xahkarias** [comment]
looks like epoe overrides all brain surgery recipes

**Comment by Xahkarias** [comment]
https://github.com/Xahkarias/EvolvedOrgansRedux/commit/b7b2d6241be287298ae6ebc3a62b2c3433abd841 fixed it
