### ISSUE TITLE
Error involving Rah's patch

### ISSUE THREAD

**Issue by elbobman2000** [Xahkarias/EvolvedOrgansRedux#5]
Just downloaded this mod and got a redtext error on startup.  Looked into it.  It appears that the patching process for RBSE compatability adds a second comps field to EVOR_OrgBase in the EVOR_Item_OrganBase.xml file.  Went and looked, and the unpatched xml has a comps on line 26 near the bottom.  Pulled that out and the redtext error went away since it wasn't seeing two of the same thing.

Is that empty comps entry necessary in the unpatched version, or can it be removed?  Most of my modding experience is reverse-engineering, so I'm unsure on that.  Thanks for the otherwise neat looking mod!

**Comment by Xahkarias** [comment]
Ah thank you for the great diagnosis, will fix

**Comment by Xahkarias** [comment]
Addressed in https://github.com/Xahkarias/EvolvedOrgansRedux/commit/c9893db5c2931311047e30a39293d0c18a03859f
