### ISSUE TITLE
issue with neural hyperthreader

### ISSUE THREAD

**Issue by BeceLblI** [Xahkarias/EvolvedOrgansRedux#57]
**expected/correct** - install neural hyperthreader does nothing with already installed things like psychic amplifier and circadian assistant.

**actual behaviour**-installed neural hyperthreader replace psychic amplifier and/or circadian assistant (may be other Royality brain upgrades).  And if you pawn have more than 1st level of psychic amplifier, levels other than the first will be lost.

**steps to reproduce the problem** - 
1) install psychic amplifier (levels 1-6) and/or other brain implants.
2) try to install in psychic ampflied pawn neural hyperthreader.

from other side: if you pawn already has neural hyperthreader - no issue with installs psychic amplifier and/or other brain implant.

**list of mods installed and their order** -
1. Harmony
2. Core
3. Royality
4. HugsLib
5. QuestionableEthicsEnhanced
6. EvolvedOrgansRedux-master

**Comment by Xahkarias** [comment]
Think i found the issue

**Comment by Xahkarias** [comment]
https://github.com/Xahkarias/EvolvedOrgansRedux/commit/33deba81500de008be6dffade108950eaa4eedba

Will be pushed to Steam tommorow
