### ISSUE TITLE
Patch Error in EVOR_Patch_0B_QEE.xml

### ISSUE THREAD

**Issue by elbobman2000** [Xahkarias/EvolvedOrgansRedux#6]
Found another.  Line 432 of the referenced file is the patch for producing the liver using QEE's organ vat.  Works great, but produces a kidney instead.

**Comment by Xahkarias** [comment]
Whoops, will fix immediately

**Comment by Xahkarias** [comment]
Implemented in https://github.com/Xahkarias/EvolvedOrgansRedux/commit/c9893db5c2931311047e30a39293d0c18a03859f
